import { Bokor, Geist, Geist_Mono, Poetsen_One, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bokorFont = Bokor({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bokor",
});
const poetsenFont = Poetsen_One({
  variable: "--font-poetsen",
  weight: "400",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bokorFont.variable} ${poetsenFont.variable} ${interFont.variable} antialiased px-4 md:px-16 relative `}
      >
        <Navbar />
        <Hero />
        <Image
          src="/images/Ellipse36.png"
          alt="ellipse"
          width={400}
          height={400}
          className="absolute top-0 left-0"
        />
        <Image
          src="/images/Ellipse37.png"
          alt="ellipse"
          width={700}
          height={700}
          className="absolute top-100  left-0"
        />
        <Image
          src="/images/Ellipse38.svg"
          alt="ellipse"
          width={400}
          height={400}
          className="absolute top-15 -translate-x-1/2 left-1/2 "
        />
        {children}
      </body>
    </html>
  );
}
